from maze_builder.sewer import MadLibs, Choice
from maze_builder.lost_text.text_decorations import fix_sentence, pluralize

clue_sentence = MadLibs(
    '{CLUE FIXED}',
    FIXED=fix_sentence,
    PLURALIZED=pluralize,
    CLUE={
        '{SOMETHING_COMES} {FROM_THAT_WAY}.': 50,
        '{ELEMENTS} form an arrow pointing {TO_THAT_WAY}.': 30,
        '{PRINTS_LEAD} {FROM_THAT_WAY} to {THAT_DOOR}.': 10,
        '{PRINTS_LEAD} {FROM_THAT_WAY}.': 10,
        '{PRINTS_LEAD} {TO_THAT_WAY}.': 20,
        '{SOMETHING_CREEPY_THAT_CAN_POINT} {POINTS_TO} {THAT_DOOR}.': 50,
        '{SOMETHING_CREEPY_THAT_CAN_POINT}.': 10,
        'I found a {NOTE}, but it was {ILLEGIBLE_OR_MESSED_UP}.': 10,
        'I found a {ILLEGIBLE} {NOTE}.': 10,
        '{THIS} {NOTE} {HELD_BY} a {DEAD_PERSON} was {ILLEGIBLE_OR_MESSED_UP}.': 10,
        'I thought this {NOTE} was {ILLEGIBLE_OR_MESSED_UP}, but it\'s proving {VERY_USEFUL}.': 10,
        'I thought this {NOTE} was {USEFUL}, but it\'s {ILLEGIBLE_OR_MESSED_UP}.': 10,
        '{THIS} {NOTE} {HELD_BY} a {DEAD_PERSON} will be {VERY_USEFUL}.': 10,
        '{THIS} {DEAD_PERSON} {WAS_HOLDING} a {ILLEGIBLE} {NOTE}.': 10,
        '{THIS} {DEAD_PERSON} {WAS_HOLDING} a {VERY_USEFUL} {NOTE}.': 10,
        '{THAT_DOOR} is covered with {RIDDLES}.': 10,
        '{RIDDLES} {ENGRAVED} here {POINT_TO} {THAT_DOOR}.': 10,
        'This {NOTE}\'s {RIDDLES} {POINT_TO} {THAT_DOOR}.': 10,
        '{RIDDLES} {ENGRAVED} here are {ILLEGIBLE}.': 10,
        '{RIDDLES} {SUGGEST} {THAT_DOOR}.': 10,
        'This {NOTE}\'s {RIDDLES} {POINT_TO} {THAT_DOOR}.': 10,
        'After solving its {RIDDLES}, this {NOTE} is {VERY_USEFUL}!': 10,
        '{RIDDING_A_PROBLEM}, I {DISCOVERED} {A_CLUE}!': 50,
        '{RIDDING_A_PROBLEM}, I took {THAT_DOOR}.': 20,
        '{RIDDING_A_PROBLEM} was no use.': 10,
        'I felt good about {RIDDING_A_PROBLEM}.': 10,
        '{RIDDING_A_PROBLEM}.': 10,
    },
    A_CLUE={
        'a {VERY_USEFUL} {NOTE}': 10,
        'a {ILLEGIBLE} {NOTE}': 10,
        '{THIS} {VERY_USEFUL} {NOTE}': 5,
        '{THIS} {ILLEGIBLE} {NOTE}': 5,
        'a {SECRET_DOOR}': 10,
    },
    SECRET_DOOR={
        'secret {DOOR}': 10,
        'magic {DOOR}': 1,
    },
    DISCOVERED={
        'discovered': 10,
        'found': 10,
        'uncovered': 10,
        'turned up': 10,
    },
    THIS={
        'the': 10,
        'a': 20,
        'this': 10,
        'some': 5,
    },
    RIDDING_A_PROBLEM={
        'clearing some vines': 10,
        'casting {THIS} spell': 10,
        'sweeping away {THIS} {DEAD_PERSON}': 2,
        'burying {THIS} {DEAD_PERSON}': 2,
        '{HUNTING} a {WILD_ANIMAL}': 10,
        '{CHASING} a {WILD_ANIMAL}': 5,
        'dissecting a {WILD_ANIMAL}': 1,
        'digging a hole': 5,
        'dusting the words {ENGRAVED} in {A_SURFACE}': 10,
        '{FOLLOWING} {A_TRAIL}': 10,
        'moving a rug': 1,
        'lifting a floorboard': 2,
    },
    A_SURFACE={
        'the wall': 10,
        'the floor': 5,
        'the ceiling': 5,
    },
    CHASING={
        'chasing': 10,
        'hunting': 10,
        'following': 10,
        'guided by': 10,
        'tracking': 10,
    },
    FOLLOWING={
        'following': 40,
        'guided by': 10,
    },
    HUNTING={
        'catching': 10,
        'snaring': 10,
        'hunting': 5,
        'killing': 2,
        'capturing': 1,
    },
    SUGGEST={
        'suggest': 30,
        'indicate': 10,
        'advise': 20,
        'commend': 5,
        'recommend': 10,
        'advocate': 5,
        'propose': 5,
        'urge': 5,
        'prescribe': 5,
        'counsel': 5,
    },
    WARN={
        'warn': 10,
        'forewarn': 5,
        'dissuade': 5,
        'caution': 10,
    },
    POINT_TO={
        '{SUGGEST}': 20,
        '{WARN} of': 10,
        '{WARN} against': 5,
        '{SUGGEST} against': 5,
    },
    POINTS_TO={
        'points to': 20,
        '{SUGGEST}s': 10,
        '{WARN}s of': 6,
        '{WARN}s against': 4,
        '{SUGGEST}s against': 4,
    },
    ENGRAVED={
        'engraved': 20,
        'painted': 10,
        'scrawled': 10,
        'carved': 5,
        'written': 1,
    },
    SOMETHING_CREEPY_THAT_CAN_POINT={
        'a {DEAD_PERSON}\'s hand': 10,
        'a broken {ARROW}': 10,
        'a {NOTE}': 5,
        'a {NOTE} {HELD_BY} a {DEAD_PERSON}': 5,
        'a {ANCIENT} engraving': 5,
        'a sharpened bone': 1,
        'an arrow of bones': 1,
        'a deactivated golem': 1,
        'a spell': 1,
    },
    USEFUL={
        'useful': 10,
        'important': 10,
        'handy': 10,
        'helpful': 10,
        'informative': 10,
    },
    VERY_USEFUL={
        '{USEFUL}': 20,
        'very {USEFUL}': 10,
        'extremely {USEFUL}': 10,
        'quite {USEFUL}': 10,
    },
    ARROW={
        'arrow': 10,
        'sundial': 10,
    },
    HOLDING={
        'holding': 10,
        'clutching': 10,
    },
    WAS_HOLDING={
        'clutched': 10,
        'held': 10,
        'held': 10,
        'was {HOLDING}': 10,
    },
    HELD_BY={
        '{CLUTCHED} by': 10,
        'found {UNDER}': 5,
    },
    UNDER={
        'under': 10,
        'around': 10,
    },
    CLUTCHED={
        'clutched': 10,
        'held': 5,
        'grasped': 1,
    },
    ILLEGIBLE_OR_MESSED_UP={
        '{ILLEGIBLE}': 10,
        '{MESSED_UP}': 10,
        'a curse on any travellers here': 1,
    },
    ILLEGIBLE={
        'illegible': 20,
        'indecipherable': 20,
        'foreign': 10,
        'irrelevant': 5,
        'misspelled': 1,
    },
    MESSED_UP={
        'written in a foreign tongue': 5,
        'filled with {RIDDLES}': 5,
        'written in code': 5,
        'wripped to shreds': 5,
        'smeared with {BODILY_FLUIDS}': 4,
        'too smeared with {BODILY_FLUIDS}': 5,
    },
    RIDDLES={
        'riddles': 30,
        'puzzles': 10,
        'mazes': 10,
        'codes': 10,
        'mysteries': 10,
        'math problems': 10,
        'hieroglyphics': 5,
    },
    NOTE={
        'note': 20,
        'letter': 10,
        'map': 15,
        'sign': 10,
        'message': 5,
        'diary': 10,
        'guidebook': 5,
        'journal': 10,
        'spell': 5,
        'spellbook': 2,
    },
    DEAD_PERSON={
        'skeleton': 10,
        'pile of bones': 10,
        'corpse': 5,
        'rotting corpse': 1,
        '{PERSON MADE_DEAD}': 40,
    },
    PERSON={
        'explorer': 10,
        'adventurer': 10,
        'thief': 10,
        'soldier': 10,
        'knight': 10,
        'maiden': 10,
        '{WILD_ANIMAL}': 20,
    },
    MADE_DEAD={
        'dead {}': 50,
        'long dead {}': 10,
        'long gone {}': 2,
        'dying {}': 5,
        'rotting {}': 10,
        '{}\'s carcass': 10,
        '{}\'s corpse': 10,
        '{}\'s skeleton': 10,
    },
    ANCIENT={
        'ancient': 10,
        'weathered': 10,
    },
    SOMETHING_COMES={
        'there\'s a {TAPPING}': 10,
        'I hear {TAPPING}': 10,
        'a wind {BLOWS}': 10,
        'the air {BLOWS}': 5,
        'something {BLOWS}': 10,
        'a voice {VOCALIZES}': 5,
        'a {WILD_ANIMAL} {VOCALIZES}': 5,
        '{BODILY_FLUIDS} {DRIPS}': 10,
    },
    TAPPING={
        'tapping': 10,
        'dripping': 10,
        'knocking': 10,
        'rustling': 10,
        'splashing': 1,
    },
    DRIPS={
        'drips': 10,
        'pools': 10,
        'splashes': 1,
    },
    BLOWS={
        'blows': 10,
        'howls': 10,
    },
    VOCALIZES={
        'howls': 10,
        'screams': 10,
        'whispers': 10,
        'cries': 5,
        'barks': 2,
        'breathes': 1,
    },
    FROM_THAT_WAY={
        'from ahead of me': 10,
        'from behind me': 10,
        'from {THAT_DOOR}': 50,
    },
    THAT_DOOR={
        'the left': 10,
        'the right': 10,
        'the left {DOOR}': 10,
        'the right {DOOR}': 10,
        'the left {HALL}': 10,
        'the right {HALL}': 10,
        'the {WAY} ahead': 10,
        'the {WAY} behind me': 10,
        'the {WAY} to the left': 20,
        'the {WAY} to the right': 20,
    },
    WAY={
        '{DOOR}': 10,
        '{DOOR ORNATE}': 20,
        '{HALL}': 10,
        '{HALL DARKENED}': 20,
    },
    DOOR={
        'door': 20,
        'doorway': 5,
        'gate': 4,
        'gateway': 1,
        'hatch': 2,
        'aperture': 1,
        'portal': 1,
        'trapdoor': 1,
    },
    ORNATE={
        'ornate {}': 10,
        'decorated {}': 10,
        'bloody {}': 10,
        'claw-marked {}': 10,
        'peeling {}': 10,
        'rusty {}': 10,
        'secret {}': 10,
    },
    HALL={
        'corridor': 10,
        'hall': 5,
        'hallway': 5,
        'way': 10,
        'path': 10,
        'passage': 5,
        'passageway': 5,
        'exit': 10,
        'entrance': 5,
        'egress': 5,
    },
    DARKENED={
        'dark {}': 10,
        'darkened {}': 10,
        'foreboding {}': 10,
        'creepy {}': 10,
        'secret {}': 10,
    },
    TO_THAT_WAY={
        'left': 10,
        'right': 10,
        'ahead': 10,
        'behind me': 10,
        'to {THAT_DOOR}': 50,
        'toward {THAT_DOOR}': 10,
    },
    ELEMENTS={
        'sticks': 10,
        'stones': 10,
        'crumbs': 5,
        'nuts': 2,
        'dead bugs': 10,
        'a {WILD_ANIMAL}\'s droppings': 10,
    },
    PRINTS_LEAD={
        '{PRINTS} {LEAD}': 10,
        '{A_TRAIL} {LEADS}': 5,
    },
    A_TRAIL={
        'a trail of {PRINTS}': 10,
        'a trail of {ELEMENTS}': 5,
        'a deliberate trail of {ELEMENTS}': 1,
        'a path of {PRINTS}': 10,
        'a trail of {BODILY_FLUIDS}': 10,
        'a line of {BODILY_FLUIDS}': 5,
    },
    BODILY_FLUIDS={
        'blood': 10,
        'slime': 10,
        'mucus': 1,
        '{RED} blood': 2,
        'fresh blood': 5,
    },
    RED={
        'red': 10,
        'crimson': 5,
    },
    PRINTS={
        'footprints': 10,
        'bare footprints': 2,
        'shoe prints': 1,
        'crumbs': 5,
        'a {WILD_ANIMAL}\'s prints': 5,
        'a {WILD_ANIMAL}\'s tracks': 5,
        'tracks': 10,
    },
    LEAD={
        'lead': 20,
        'head': 10,
        'come': 10,
        'go': 5,
    },
    LEADS={
        'leads': 50,
        'points': 30,
        'heads': 10,
        'goes': 10,
    },
    WILD_ANIMAL={
        'wild animal': 10,
        'deer': 10,
        'dog': 20,
        'wolf': 20,
        'fox': 10,
        'giant hare': 10,
        'direwolf': 5,
        'owlbear': 5,
        'bear': 10,
        'ape': 10,
        'buzzard': 5,
        'kobold': 1,
    },
)

if __name__ == '__main__':
    for _ in range(20):
        print(clue_sentence())
