from maze_builder.sewer import MadLibs, Choice
from maze_builder.lost_text.text_decorations import strike, fix_sentence, pluralize

missing_sentence = MadLibs({
        '{MISSING_SENTENCE FIXED}': 70,
        '{MISSING_SENTENCE FIXED STRUCK}': 30,
    },
    STRUCK=strike,
    FIXED=fix_sentence,
    PLURALIZED=pluralize,
    MISSING_SENTENCE={
        '{MISSING} {A_LOST_THING}.': 50,
        '{WANTING_BADLY} my {RELATION}.': 20,
        '{SHALL} I ever see my {RELATION} again?': 10,
        '{IM_AFRAID} I {SHALL} never see my {RELATION} again.': 10,
        'I\'ll never see my {RELATION} again.': 10,
        'Is my {RELATION} {STILL_ALIVE}?': 10,
        'My {RELATION} must {MISS_ME}.': 20,
        'Remember me, {RELATION}.': 10,
        'Don\'t {FORGET_ME}, {RELATION}.': 10,
        'I\'ll find you, {RELATION}.': 20,
        'Believe in me, {RELATION}.': 1,
        'Tell my {MALE_PARTNER} I {MISS} him.': 3,
        'Tell my {FEMALE_PARTNER} I {MISS} her.': 3,
        'Tell my {ANY_PARTNER} I {MISS} {THEM}.': 3,
        '{GO_ON_WITHOUT_ME}, {RELATION}.': 5,
    },
    IM_AFRAID={
        'I\'m afraid': 10,
        'I fear': 10,
        'worried': 5,
    },
    THEM={
        'them': 10,
        'him': 5,
        'her': 5,
        'zir': 1,
        'hir': 1,
    },
    GO_ON_WITHOUT_ME={
        'forget me': 10,
        'I hope you\'ve moved on': 10,
        'make peace with my absence': 10,
        'you\'ll never see me': 1,
    },
    FORGET_ME={
        'give up hope': 10,
        'forget me': 10,
        'leave me here': 1,
    },
    MISSING={
        'I miss': 10,
        'missing': 10,
        'remembering': 5,
        'dreamed about': 10,
        'barely remember': 2,
        'I can\'t remember': 2,
        'I can\'t forget': 2,
    },
    STILL_ALIVE={
        '{STILL_}alive': 10,
        '{STILL_}kicking': 1,
        'waiting for me': 10,
        '{STILL_}hoping for my return': 10,
        'awaiting my return': 10,
    },
    STILL_={
        'still ': 10,
        'even ': 5,
    },
    MISS_ME={
        'miss me': 10,
        'think I\'m dead': 10,
        'consider me gone': 10,
        'still be waiting': 5,
    },
    WANTING_BADLY={
        '{LIGHTING_A_CANDLE} in memory of': 10,
        '{LIGHTING_A_CANDLE} for': 10,
        'crying for': 10,
        'longing for': 10,
        '{MISSING}': 10,
    },
    LIGHTING_A_CANDLE={
        'lighting a candle': 10,
        'praying': 5,
        'saying a prayer': 5,
        'crying': 2,
        'writing a poem': 5,
    },
    SHALL={
        'shall': 10,
        'will': 10,
        'can': 2,
    },
    MISS={
        'miss': 10,
        'crave': 5,
        'long for': 10,
        'yearn for': 2,
    },
    A_LOST_THING={
        'my {RELATION}\'s {ATTRIBUTE}': 30,
        'my {PARTNER}\'s {PARTNER_ATTRIBUTE}': 30,
        'my {RELATION}': 30,
        'reading new stories': 1,
        'the outside world': 1,
        'the way things were before': 1,
        'my youth': 1,
        'visiting my {RELATION}\'s grave': 3,
        'visiting my {RELATION}': 3,
        'drinking with my {RELATION}': 5,
        'drinking {LIBATIONS} with my {RELATION}': 5,
        'smoking with my {RELATION}': 5,
        'eating with my {RELATION}': 3,
        'hunting with my {RELATION}': 1,
        'hiking with my {RELATION}': 1,
        'fighting my {RELATION}': 3,
        'losing my {RELATION}': 1,
        'talking to my {RELATION}': 3,
        'chatting with my {RELATION}': 3,
        'exchanging gifts with my {RELATION}': 1,
        'tutoring my {RELATION}': 1,
        'cuddling with my {PARTNER}': 3,
        'spooning with my {PARTNER}': 3,
        'making love to my {PARTNER}': 3,
        'fresh food': 1,
        'seeing art': 1,
        'fresh air': 1,
        'hope': 1,
        'cigarettes': 1,
        'beer': 2,
        'alcohol': 1,
    },
    LIBATIONS={
        'beer': 10,
        'alcohol': 2,
        'wine': 5,
        'whiskey': 5,
    },
    RELATION={
        'friend': 10,
        'buddy': 10,
        'partner': 10,
        'wife': 10,
        'husband': 10,
        'boyfriend': 10,
        'girlfriend': 10,
        'boy': 10,
        'girl': 10,
        'child': 10,
        'son': 10,
        'daughter': 10,
        'pet': 5,
        'cat': 10,
        'dog': 10,
        'father': 5,
        'mother': 5,
        'parent': 5,
        'grandma': 2,
        'grandpa': 2,
        'nana': 2,
        'papa': 5,
        'dad': 5,
        'daddy': 5,
        'mom': 5,
        'mommy': 5,
        'mistress': 2,
        '{PARTNER}': 5,
    },
    MALE_PARTNER={
        'husband': 20,
        'boyfriend': 20,
        'pool boy': 1,
    },
    FEMALE_PARTNER={
        'wife': 20,
        'girlfriend': 20,
        'mistress': 1,
    },
    ANY_PARTNER={
        'partner': 10,
        'spouse': 5,
        'ex': 1,
    },
    PARTNER={
        '{MALE_PARTNER}': 10,
        '{FEMALE_PARTNER}': 10,
        '{ANY_PARTNER}': 10,
    },
    PARTNER_ATTRIBUTE={
        'kiss': 40,
        'love': 20,
        '{ATTRIBUTE}': 30,
        'lovemaking': 5,
        'loving ways': 5,
        'beauty': 10,
        'caress': 20,
        'embrace': 20,
        'cuddles': 5,
        'affection': 3,
        'devotion': 1,
        'passion': 5,
        'smell': 10,
        'hair': 1,
        'eyes': 1,
        'compliments': 1,
        'presence': 5,
    },
    ATTRIBUTE={
        'smile': 30,
        'laugh': 10,
        'laughter': 10,
        'jokes': 10,
        'kindness': 15,
        'gentleness': 10,
        'wisdom': 5,
        'caring ways': 10,
        'face': 20,
        'grin': 1,
        'patience': 1,
    },
)

if __name__ == '__main__':
    for _ in range(20):
        print(missing_sentence())
