from maze_builder.sewer import MadLibs, Choice
from maze_builder.lost_text.text_decorations import fix_sentence

nasty_room_sentence = MadLibs(
    '{ROOM NASTY SENTENCE FIXED}',
    FIXED=fix_sentence,
    SENTENCE={
        "A {}.": 15,
        "{}.": 5,
        "Another {}.": 8,
        "I'll stay in this {} a while.": 1,
        "Should I spend the night in this {}?": 1,
        "I awoke in this {}.": 1,
        "Yet another {}.": 3,
        "I tire of coming across another {}.": 0.5,
        "Not another {}!": 1,
        "I find myself in a {}.": 1,
        "Setting up camp in this {}.": 1,
        "Taking a break in this {}.": 1,
        "Sitting in a {}.": 1,
        "Searched a {}.": 1,
        "Found a {}.": 1,
        "Claiming this {}.": 1,
        "I remember this {}.": 1,
        "This {} again?": 1,
        "Fell into a {}.": 1,
        "Lunched in a {}.": 1,
        "Snacking in a {}.": 1,
    },
    NASTY={
        '{}': 15,
        'musty {}': 1,
        'dusty {}': 1,
        'horrid {}': 1,
        'awful {}': 1,
        'unpleasant {}': 1,
        'unlit {}': 1,
        'dark {}': 1,
        'drafty {}': 1,
        'comfortless {}': 1,
        'little {}': 1,
        'dusty {}': 1,
        'forsaken {}': 1,
        'lonely {}': 1,
        'uninhabited {}': 1,
        'unwelcoming {}': 1,
        'chilly {}': 1,
        'godforsaken {}': 1,
        'featureless {}': 1,
        'abandoned {}': 1,
        'deserted {}': 1,
        '{} like any other': 1,
    },
    ROOM={
        'room': 10,
        'place': 5,
        'space': 10,
        'cell': 5,
        'alcove': 5,
        'chamber': 10,
        'corridor': 10,
        'hallway': 10,
        'hall': 10,
        'passage': 10,
        'area': 10,
        'lobby': 2,
        'entry': 2,
        'hole': 1,
        'maze': 1,
        'entranceway': 5,
    },
)
