from maze_builder.sewer import MadLibs, Choice
from maze_builder.lost_text.text_decorations import fix_sentence


negative_status_sentence = MadLibs({
        '{NEGATIVE_STATUS INTENSIFIED SENTENCE FIXED}': 1,
        '{NEGATIVE_STATUS SENTENCE FIXED}': 1,
    },
    FIXED=fix_sentence,
    SENTENCE={
        '{}.': 30,
        '{}!': 10,
        '{} again?': 10,
        '{} now.': 2,
        '{} here.': 5,
        '{} here!': 2,
        '{}. Now I know what that means.': 1,
        '{}: and not for the first time.': 1,
        '{} -- and not for the first time.': 1,
        '{}? Yes, always.': 1,
        'I feel {}.': 10,
        'I feel so {}.': 5,
        'I feel so {}!': 5,
        'I\'m {}.': 10,
        'I\'m so {}.': 5,
        'Will I always be so {}?': 1,
        'Why am I so {}?': 1,
        'No one knows how {} I am.': 1,
        'Has anyone ever been so {} before?': 1,
        'Has anyone ever been so {}?': 1,
        'Has anyone ever felt so {}?': 1,
        'I never want to feel this {} again.': 1,
        'I hope I\'ll never be so {} again.': 1,
        'I can\'t stand being so {}.': 1,
        'I\'ve never been so {}.': 1,
        'I\'ve never been so {} before.': 1,
        'Before this trip, I\'d never been so {}.': 1,
        'At home, no one is ever so {}.': 1,
        'So {} a person can be.': 1,
        'So {} a person can feel.': 1,
        'We weren\'t meant to feel so {}.': 1,
        'I never knew what it was like to be so {}.': 1,
        'No one has ever been so {}.': 1,
        'I could write a book about being so {}.': 1,
        'Even in my dreams, I\'m {}.': 1,
        'I\'m as {} as I\'ve ever been.': 1,
        'Why does God allow us to be so {}?': 1,
        'Would I have come this way, if I\'d known I\'d be so {}?': 1,
    },
    INTENSIFIED={
        'awfully {}': 1,
        'amazingly {}': 1,
        'cursedly {}': 1,
        'critically {}': 1,
        'deathly {}': 1,
        'meagerly {}': 0.2,
        'super-{}': 1,
        'devastatingly {}': 1,
        'terribly {}': 1,
        'dreadfully {}': 1,
        'wickedly {}': 1,
        'disgracefully {}': 1,
        'completely {}': 1,
        'reprehensibly {}': 1,
        'unforgivably {}': 1,
        'unpleasantly {}': 1,
        'wretchedly {}': 1,
    },
    NEGATIVE_STATUS={  # Used as '{}' or 'I'm so {}...'
        'hungry': 2,
        'cold': 2,
        'tired': 5,
        'exhausted': 1,
        'defeated': 1,
        'worn out': 1,
        'ravenous': 1,
        'faint': 1,
        'empty': 1,
        'hollow': 1,
        'insatiable': 1,
        'famished': 1,
        'unsatisfied': 1,
        'beat': 1,
        'annoyed': 1,
        'bored': 2,
        'distressed': 1,
        'drained': 1,
        'exasperated': 1,
        'fatigued': 1,
        'sleepy': 1,
        'collapsing': 1,
        'jaded': 1,
        'overtaxed': 1,
        'spent': 1,
        'wasted': 1,
        'worn': 1,
        'burned out': 1,
        'done for': 1,
        'lost': 20,
        'desolate': 1,
        'lonesome': 1,
        'alone': 1,
        'spiritless': 1,
        'sick and tired': 1,
        'sick': 1,
        'unenthusiastic': 1,
        'unenergetic': 1,
        'adrift': 1,
        'disoriented': 5,
        'astray': 1,
        'off-course': 5,
        'perplexed': 2,
        'bewildered': 2,
        'confused': 5,
        'contrite': 1,
        'unsettled': 1,
        'puzzled': 5,
        'ailing': 1,
        'ill': 1,
        'debilitated': 1,
        'frail': 1,
        'impaired': 1,
        'nauseated': 2,
        'bedridden': 1,
        'not so hot': 1,
        'under the weather': 1,
        'run down': 1,
        'unhealthy': 1,
        'unwell': 1,
        'weak': 1,
        'laid-up': 1,
        'rotten': 1,
        'anemic': 1,
        'feeble': 1,
        'confused': 10,
        'fragile': 1,
        'hesitant': 2,
        'powerless': 1,
        'uncertain': 5,
        'shaky': 1,
        'sickly': 1,
        'sluggish': 1,
        'slow': 1,
        'unsteady': 1,
        'weakened': 1,
        'wobbly': 1,
        'puny': 1,
        'out of gas': 1,
        'irresolute': 1,
        'spent': 1,
        'infirm': 1,
        'chilled': 1,
        'frozen': 1,
        'frigid': 1,
        'raw': 1,
        'numbed': 1,
        'benumbed': 1,
        'thirsty': 1,
        'parched': 1,
        'injured': 5,
        'afraid': 5,
        'terrified': 1,
        'anxious': 1,
        'apprehensive': 1,
        'frightened': 1,
        'nervous': 1,
        'scared': 1,
        'cowardly': 1,
        'daunted': 1,
        'discouraged': 1,
        'disheartened': 1,
        'dismayed': 1,
        'distressed': 1,
        'horrified': 1,
        'panic-stricken': 1,
        'petrified': 1,
        'scared stiff': 1,
        'scared to death': 1,
        'terror-stricken': 1,
        'humbled': 1,
        'dead': 1,
        'naked': 1,
        'wild': 1,
        'uncivilized': 1,
        'scorched': 1,
        'withered': 1,
        'sunburned': 1,
        'windburned': 1,
        'frostbitten': 1,
        'dehydrated': 1,
        'shriveled': 1,
        'dried up': 1,
        'dried out': 1,
        'smelly': 1,
        'stinky': 1,
        'noxious': 1,
        'putrid': 1,
        'revolting': 1,
        'grody': 1,
        'gross': 1,
        'icky': 1,
    }
)
